name: amn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - tensorflow=2.6
  - numpy=1.20.3
  - pandas
  - cobra
  - scikit-learn
  - keras=2.6
  - matplotlib
  - seaborn
  - pydoe2
  - pip
  - ipykernel
  - pip:
    - silence-tensorflow